name: Feature request
description: Propose a new capability or improvement for cbash-cli.
title: "[Feature]: "
labels:
  - enhancement
body:
  - type: markdown
    attributes:
      value: |
        Help us evaluate this request with concrete use cases and tradeoffs.
  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: One-line statement of the requested capability.
      placeholder: Add a command to list all repos with uncommitted changes.
    validations:
      required: true
  - type: textarea
    id: problem
    attributes:
      label: Problem to solve
      description: What user pain this solves and why current behavior is insufficient.
      placeholder: Need to see which repos are dirty before running gitfor; currently must cd into each or use custom script.
    validations:
      required: true
  - type: textarea
    id: proposed_solution
    attributes:
      label: Proposed solution
      description: Desired behavior/command/UX with as much specificity as possible.
      placeholder: New command e.g. gitstatus_all that prints repo path and short status; support --porcelain for scripting.
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
      description: Other approaches considered and why they are weaker.
      placeholder: Wrapping gitfor "git status" is too noisy; custom alias is not discoverable.
  - type: textarea
    id: impact
    attributes:
      label: Impact
      description: |
        Who is affected, severity/urgency, how often this pain occurs, and practical consequences.
        - Affected users/setups (e.g. plugin, shell, OS)
        - Severity (nice-to-have, blocks workflow, etc.)
        - Frequency (daily / occasional / edge case)
        - Consequence (time saved, fewer errors, etc.)
      placeholder: |
        Affected: Users with many repos (git plugin)
        Severity: Medium
        Frequency: Daily before batch operations
        Consequence: Faster triage, fewer mistakes
    validations:
      required: true
  - type: textarea
    id: evidence
    attributes:
      label: Evidence/examples
      description: Prior art, links, sample commands, or screenshots.
      placeholder: Similar behavior in tool X; example desired output.
  - type: textarea
    id: additional_information
    attributes:
      label: Additional information
      description: Extra context, constraints, or references not covered above.
      placeholder: Should work with both Bash and Zsh; backward-compatible with existing plugins.
