services:
  localstack:
    container_name: localstack
    image: localstack/localstack
    hostname: localstack
    environment:
      - SERVICES=s3,sqs,sns,ssm
      - DEBUG=1
      - DATA_DIR=/tmp/localstack/data
      - AWS_DEFAULT_REGION=eu-west-1
      - EDGE_PORT=4566
    ports:
      - '4566:4566'  # Main edge port
      - '4571:4571'  # Additional required port
      - '8055:8080'  # Web UI
    volumes:
      - ${DEV_VOLUMES_ASSET_DIR:-./volumes}/localstack:/tmp/localstack/data
    networks:
      - infra-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4566/health"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 15s
    deploy:
      resources:
        limits:
          memory: 4G

  zookeeper:
    hostname: zookeeper
    container_name: zookeeper
    image: bitnami/zookeeper:latest
    platform: linux/arm64
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    networks:
      - infra-network
    volumes: 
      - ${DEV_VOLUMES_ASSET_DIR:-./volumes}/zookeeper/data:/bitnami/zookeeper
    healthcheck:
      test: ["CMD-SHELL", "echo srvr | nc localhost 2181 || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    deploy:
      resources:
        limits:
          memory: 512M

  kafka:
    container_name: kafka
    hostname: kafka
    image: bitnami/kafka:latest
    platform: linux/arm64
    depends_on:
      zookeeper:
        condition: service_healthy
    ports:
      - '9092:9092'
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,INTERNAL://:29092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092,INTERNAL://kafka:29092
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,INTERNAL:PLAINTEXT
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=INTERNAL
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true
      - KAFKA_CFG_DELETE_TOPIC_ENABLE=true
      - KAFKA_CFG_OFFSETS_TOPIC_REPLICATION_FACTOR=1
      - ALLOW_PLAINTEXT_LISTENER=yes
    networks:
      - infra-network
    volumes:
      - ${DEV_VOLUMES_ASSET_DIR:-./volumes}/kafka:/bitnami/kafka
    healthcheck:
      test: ["CMD-SHELL", "kafka-topics.sh --bootstrap-server localhost:9092 --list"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 15s
    deploy:
      resources:
        limits:
          memory: 4G

  mysql:
    image: mysql:8.0
    container_name: mysql
    platform: linux/arm64
    environment:
      MYSQL_ROOT_PASSWORD: root          # Change this! (password: root)
      MYSQL_DATABASE: mydatabase         # Optional default database
      MYSQL_USER: myuser                 # Optional custom user
      MYSQL_PASSWORD: mypassword         # Change this!
    ports:
      - "3306:3306"
    volumes:
      - ${DEV_VOLUMES_ASSET_DIR:-./volumes}/mysql:/var/lib/mysql
    networks:
      - infra-network
    restart: always
    deploy:
      resources:
        limits:
          memory: 4G

networks:
  infra-network:
    name: infra-network
    driver: bridge
